version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: haatbazar
      POSTGRES_PASSWORD: haatbazar
      POSTGRES_DB: haatbazar
    ports:
      - "5432:5432"
    volumes:
      - haatbazar_pgdata:/var/lib/postgresql/data

volumes:
  haatbazar_pgdata:
